meta_product_name: "FOOTCH."
meta_title: "FOOTCH. | Tell me what's' in your fridge, I'll tell you what you can cook."
meta_description: "Footch is a webapp that helps you find recipes according to the ingredients available in your fridge. Don't spend hours on the web trying to find the right meal for tonight. Footch will do it for you!"
meta_image: "footch.jpg"
